# Generated by cpp11: do not edit by hand

solve_nai_arma_ <- function(a, b) {
  .Call(`_psarrasadaptation_solve_nai_arma_`, a, b)
}

solve_rec_arma_ <- function(a, b) {
  .Call(`_psarrasadaptation_solve_rec_arma_`, a, b)
}

solve_nai_eigen_ <- function(a, b) {
  .Call(`_psarrasadaptation_solve_nai_eigen_`, a, b)
}

solve_rec_eigen <- function(a, b) {
  .Call(`_psarrasadaptation_solve_rec_eigen`, a, b)
}
