// Generated by cpp11: do not edit by hand
// clang-format off


#include "cpp11/declarations.hpp"
#include <R_ext/Visibility.h>

// 01-arma-functions.cpp
doubles_matrix<> solve_nai_arma_(const doubles_matrix<>& a, const doubles_matrix<>& b);
extern "C" SEXP _psarrasadaptation_solve_nai_arma_(SEXP a, SEXP b) {
  BEGIN_CPP11
    return cpp11::as_sexp(solve_nai_arma_(cpp11::as_cpp<cpp11::decay_t<const doubles_matrix<>&>>(a), cpp11::as_cpp<cpp11::decay_t<const doubles_matrix<>&>>(b)));
  END_CPP11
}
// 01-arma-functions.cpp
doubles_matrix<> solve_rec_arma_(const doubles_matrix<>& a, const doubles_matrix<>& b);
extern "C" SEXP _psarrasadaptation_solve_rec_arma_(SEXP a, SEXP b) {
  BEGIN_CPP11
    return cpp11::as_sexp(solve_rec_arma_(cpp11::as_cpp<cpp11::decay_t<const doubles_matrix<>&>>(a), cpp11::as_cpp<cpp11::decay_t<const doubles_matrix<>&>>(b)));
  END_CPP11
}
// 02-eigen-functions.cpp
doubles_matrix<> solve_nai_eigen_(const doubles_matrix<>& a, const doubles_matrix<>& b);
extern "C" SEXP _psarrasadaptation_solve_nai_eigen_(SEXP a, SEXP b) {
  BEGIN_CPP11
    return cpp11::as_sexp(solve_nai_eigen_(cpp11::as_cpp<cpp11::decay_t<const doubles_matrix<>&>>(a), cpp11::as_cpp<cpp11::decay_t<const doubles_matrix<>&>>(b)));
  END_CPP11
}
// 02-eigen-functions.cpp
doubles_matrix<> solve_rec_eigen(const doubles_matrix<>& a, const doubles_matrix<>& b);
extern "C" SEXP _psarrasadaptation_solve_rec_eigen(SEXP a, SEXP b) {
  BEGIN_CPP11
    return cpp11::as_sexp(solve_rec_eigen(cpp11::as_cpp<cpp11::decay_t<const doubles_matrix<>&>>(a), cpp11::as_cpp<cpp11::decay_t<const doubles_matrix<>&>>(b)));
  END_CPP11
}

extern "C" {
static const R_CallMethodDef CallEntries[] = {
    {"_psarrasadaptation_solve_nai_arma_",  (DL_FUNC) &_psarrasadaptation_solve_nai_arma_,  2},
    {"_psarrasadaptation_solve_nai_eigen_", (DL_FUNC) &_psarrasadaptation_solve_nai_eigen_, 2},
    {"_psarrasadaptation_solve_rec_arma_",  (DL_FUNC) &_psarrasadaptation_solve_rec_arma_,  2},
    {"_psarrasadaptation_solve_rec_eigen",  (DL_FUNC) &_psarrasadaptation_solve_rec_eigen,  2},
    {NULL, NULL, 0}
};
}

extern "C" attribute_visible void R_init_psarrasadaptation(DllInfo* dll){
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
  R_forceSymbols(dll, TRUE);
}
